/* Write your PL/SQL query statement below */
SELECT T1.REPORTS_TO AS EMPLOYEE_ID,
(SELECT NAME FROM EMPLOYEES T2 WHERE T1.REPORTS_TO = T2.EMPLOYEE_ID) AS NAME,
COUNT(T1.EMPLOYEE_ID) AS REPORTS_COUNT, 
ROUND(AVG(T1.AGE)) AS AVERAGE_AGE
FROM EMPLOYEES T1
WHERE T1.REPORTS_TO IS NOT NULL
GROUP BY T1.REPORTS_TO
ORDER BY T1.REPORTS_TO;